# Generated by Django 4.2.20 on 2025-04-27 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_hash",
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="is_duplicate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="file",
            name="reference_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicates",
                to="files.file",
            ),
        ),
    ]
