# Generated by Django 4.2.20 on 2025-04-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_file_file_hash_file_is_duplicate_file_reference_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="storage_saved",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="file",
            name="file_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
