# Generated by Django 4.2.20 on 2025-04-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_remove_file_is_duplicate_remove_file_reference_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file_type",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="file",
            name="original_filename",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="file",
            name="size",
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="file",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
