# Generated by Django 4.2.20 on 2025-04-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0006_tag_file_description_file_last_accessed_file_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="last_accessed",
        ),
        migrations.AddField(
            model_name="file",
            name="content_category",
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="file_extension",
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="file",
            name="last_modified",
            field=models.DateTimeField(null=True),
        ),
        migrations.RemoveField(
            model_name="file",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.AddField(
            model_name="file",
            name="tags",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
